CREATE CONSTRAINT memory_id IF NOT EXISTS
FOR (m:Memory)
REQUIRE m.id IS UNIQUE;
CREATE CONSTRAINT wing_name IF NOT EXISTS
FOR (w:Wing)
REQUIRE w.name IS UNIQUE;
CREATE CONSTRAINT room_key IF NOT EXISTS
FOR (r:Room)
REQUIRE r.key IS UNIQUE;
CREATE CONSTRAINT closet_key IF NOT EXISTS
FOR (c:Closet)
REQUIRE c.key IS UNIQUE;
CREATE CONSTRAINT drawer_key IF NOT EXISTS
FOR (d:Drawer)
REQUIRE d.key IS UNIQUE;
CREATE CONSTRAINT person_name IF NOT EXISTS
FOR (p:Person)
REQUIRE p.name IS UNIQUE;
CREATE CONSTRAINT topic_name IF NOT EXISTS
FOR (t:Topic)
REQUIRE t.name IS UNIQUE;
CREATE CONSTRAINT project_name IF NOT EXISTS
FOR (p:Project)
REQUIRE p.name IS UNIQUE;
CREATE CONSTRAINT tag_name IF NOT EXISTS
FOR (t:Tag)
REQUIRE t.name IS UNIQUE;
CREATE CONSTRAINT source_file_path IF NOT EXISTS
FOR (s:SourceFile)
REQUIRE s.path IS UNIQUE;
